src/article/preview/ArticlePreviewDensedLayout.module.scss, src/article/preview/ArticlePreviewStandardLayout.tsx, src/shared/edit/EditOverlay.module.scss, src/shared/edit/EditOverlay.tsx, src/shared/edit/SelectFileOverlay.tsx
=> 950 unterste zeile im vorschautext in kompaktansicht leicht angeschnitten

src/messaging/CreateMessageDialog.tsx
=> added blank between user icon and user name, enlarged user icon

src/administration/users/GroupList.module.scss
https://gitlab.com/lotta-schule/web-client/-/issues/688
=> optimized style for group selection in admin view

src/messaging/ComposeMessage.module.scss, src/messaging/MessageToolbar.module.scss, src/messaging/MessageToolbar.tsx, src/messaging/MessagingView.module.scss, src/messaging/MessagingView.tsx
-> orig. ticket for branch at GitLab: https://gitlab.com/lotta-schule/web-client/-/issues/892
=> mobile: optimized style for messenger

packages/storybook-hubert/src/layout/List.stories.tsx, packages/storybook-hubert/src/layout/Stepper.stories.tsx, packages/storybook-hubert/src/user/Avatar.stories.tsx, packages/storybook-hubert/src/user/AvatarGroup.stories.tsx, packages/storybook-hubert/src/util/Deletable.stories.tsx, packages/webapp/src/administration/users/GroupList.tsx, packages/webapp/src/util/model/User.ts
=> Fix dicebear avataaars avatar URL

packages/webapp/src/profile/component/ProfileDeleteFileSelection.test.tsx, packages/webapp/src/shared/fileExplorer/DeleteDirectoryDialog.module.scss, packages/webapp/src/shared/fileExplorer/DeleteDirectoryDialog.test.tsx, packages/webapp/src/shared/fileExplorer/DeleteDirectoryDialog.tsx, packages/webapp/src/shared/fileExplorer/DirectoryTableRow.tsx, packages/webapp/src/shared/fileExplorer/FileExplorer.tsx, packages/webapp/src/shared/fileExplorer/MoveDirectoryDialog.test.tsx, packages/webapp/src/shared/fileExplorer/context/FileExplorerContext.ts, packages/webapp/src/shared/fileExplorer/context/reducer.ts, packages/webapp/src/test/fixtures/Accounts.ts
=> Add Possibility to recursivly delete directories

packages/webapp/src/api/client.ts
=> fix(webapp): Include headers to api request case-insensitivly

packages/webapp/src/shared/edit/GroupSelect.module.scss, packages/webapp/src/shared/edit/GroupSelect.tsx
Update broke GroupSelect in various locations
Resolves #74
=> revert: 8d0a3d18cc50f61f85d91252456bfd4572c20ca3

packages/webapp/src/pages/_app.tsx
=> Fix(webapp): Fixes error when tenant is not set, bringing back special screen

packages/hubert/src/layout/Toolbar.module.scss, packages/webapp/src/administration/users/GroupList.module.scss, packages/webapp/src/administration/users/GroupList.tsx, packages/webapp/src/administration/users/UserList.module.scss, packages/webapp/src/administration/users/UserList.test.tsx, packages/webapp/src/administration/users/UserList.tsx, packages/webapp/src/shared/edit/GroupSelect.module.scss
Für GroupList Komponente:
Prinzip der Nachrichtenübersichtsseite übernehmen:
- Wenn Liste sichtbar: Pfeil rechts zum Einblenden der Gruppeninfo
- Wenn Gruppeninfo sichtbar: Pfeil links zum Einblenden der Liste
=> WIP: added toolbar component for UserList and GroupList in admin section

packages/hubert/src/badge/Badge.tsx, packages/webapp/src/administration/AdminPage.test.tsx, packages/webapp/src/administration/AdminPage.tsx, packages/webapp/src/administration/Navigation.tsx, packages/webapp/src/api/query/GetFeedbackOverviewQuery.graphql, packages/webapp/src/layout/navigation/UserNavigation.test.tsx, packages/webapp/src/layout/navigation/UserNavigation.tsx, packages/webapp/src/layout/navigation/UserNavigationMobile.test.tsx, packages/webapp/src/layout/navigation/UserNavigationMobile.tsx, packages/webapp/src/profile/ProfilePage.test.tsx, packages/webapp/src/test/util.tsx, packages/webapp/src/util/feedback/index.ts, packages/webapp/src/util/feedback/useNewFeedbackCount.test.ts, packages/webapp/src/util/feedback/useNewFeedbackCount.ts, packages/webapp/src/util/user/index.ts
=> Feat(webapp): Add badge icons to admin-link and on admin-page for new feedback

packages/webapp/src/administration/system/Feedback.module.scss, packages/webapp/src/administration/system/Feedback.tsx, packages/webapp/src/administration/system/feedback/DeleteFeedbackDialog.test.tsx, packages/webapp/src/administration/system/feedback/DeleteFeedbackDialog.tsx, packages/webapp/src/administration/system/feedback/FeedbackRow.test.tsx, packages/webapp/src/administration/system/feedback/FeedbackRow.tsx, packages/webapp/src/api/mutation/DeleteFeedbackMutation.graphql, packages/webapp/src/api/schema.graphql
=> Feat(webapp): Allow feedback deletion

packages/webapp/src/administration/shared.module.scss, packages/webapp/src/administration/system/Presentation.tsx
=> Fix(webapp): Admin: Presentation: Fix overflowing content in template selection to scroll

packages/webapp/src/privacy/PrivacyPage.tsx
=> feat(webapp): Update privacy policy

packages/webapp/src/article/tagDetailsDialog/TagDetailsDialog.test.tsx, packages/webapp/src/article/tagDetailsDialog/TagDetailsDialog.tsx, packages/webapp/src/profile/userArticlesDialog/UserArticlesDialog.test.tsx, packages/webapp/src/profile/userArticlesDialog/UserArticlesDialog.tsx
=> Feat(webapp): Close UserArticlesDialog and TagDetailsDialog on navigation

packages/webapp/src/privacy/PrivacyPage.tsx
- redundant text deleted
- space after list
- changed "Du" to the polite form "Sie"
=> privacy policy: correction of content

packages/webapp/src/administration/AdminPage.module.scss, packages/webapp/src/administration/categories/WidgetList.tsx, packages/webapp/src/administration/users/GroupList.tsx, packages/webapp/src/messaging/MessagesThread.tsx, packages/webapp/src/messaging/MessagingPage.tsx
=> fix(webapp): mark scrollable toolbars as such so they do not 'hang low'

packages/hubert/src/drawer/Drawer.module.scss, packages/webapp/src/category/widgetsList/WidgetsList.tsx, packages/webapp/src/layout/navigation/Footer.module.scss, packages/webapp/src/layout/navigation/Footer.tsx
Fixes https://github.com/lotta-schule/web/issues/165
=> feat(webapp): Make Footer fit better with many links

packages/hubert/src/drawer/Drawer.tsx, packages/hubert/src/util/index.ts, packages/hubert/src/util/usePreventScroll.tsx, packages/webapp/src/category/widgetsList/WidgetsList.tsx
=> fix(webapp): Do not scroll body when drawer is open

packages/hubert/src/layout/splitView/SplitView.module.scss, packages/hubert/src/layout/splitView/SplitView.tsx, packages/hubert/src/layout/splitView/SplitViewNavigation.tsx, packages/webapp/src/administration/AdminPage.module.scss
=> fix(webapp): Add admin padding back

packages/hubert/src/layout/splitView/SplitView.module.scss, packages/hubert/src/layout/splitView/SplitViewContext.tsx, packages/hubert/src/util/useElementFullWindowHeight.ts, packages/webapp/src/administration/categories/WidgetList.tsx, packages/webapp/src/administration/categories/categories/CategoryNavigation.tsx, packages/webapp/src/administration/users/GroupList.tsx, packages/webapp/src/messaging/MessagingView.tsx
=> fix(webapp): Use IntersectionObserver for Splitview and add padding

packages/hubert/src/list/ListItemSecondaryText.tsx, packages/webapp/src/messaging/ConversationPreview.tsx, packages/webapp/src/messaging/MessagingView.module.scss, packages/webapp/src/messaging/MessagingView.tsx
=> fix(webapp): Remove padding in Messaging sidebar

packages/hubert/jest.setup.ts, packages/hubert/src/button/BaseButton.module.scss, packages/hubert/src/button/Button.module.scss, packages/hubert/src/button/LoadingButton.module.scss, packages/hubert/src/button/LoadingButton.test.tsx, packages/hubert/src/button/LoadingButton.tsx, packages/hubert/src/icon/ArrowUpwardRounded.tsx, packages/hubert/src/icon/Check.tsx, packages/hubert/src/icon/ChevronRight.tsx, packages/hubert/src/icon/Close.tsx, packages/hubert/src/icon/DragHandle.tsx, packages/hubert/src/icon/ExpandMore.tsx, packages/hubert/src/icon/KeyboardArrowLeft.tsx, packages/hubert/src/icon/KeyboardArrowRight.tsx, packages/hubert/src/progress/CircularProgress.tsx, packages/hubert/src/test-utils.tsx, packages/storybook-hubert/src/buttons/BaseButton.stories.tsx, packages/storybook-hubert/src/buttons/LoadingButton.stories.tsx, packages/webapp/jest.setup.ts, packages/webapp/src/administration/system/feedback/DeleteFeedbackDialog.tsx, packages/webapp/src/administration/users/DeleteUserGroupDialog.tsx, packages/webapp/src/administration/users/EditUserGroup.module.scss, packages/webapp/src/administration/users/EditUserGroup.tsx, packages/webapp/src/shared/dialog/LoginDialog.test.tsx, packages/webapp/src/shared/dialog/LoginDialog.tsx, packages/webapp/src/shared/dialog/RegisterDialog.tsx, packages/webapp/src/shared/fileExplorer/DeleteDirectoryDialog.test.tsx, packages/webapp/src/shared/fileExplorer/DeleteDirectoryDialog.tsx
=> feat(hubert): Update LoadingButton component to support icons+state

packages/webapp/src/administration/users/DeleteUserGroupDialog.test.tsx, packages/webapp/src/administration/users/DeleteUserGroupDialog.tsx, packages/webapp/src/administration/users/EditUserGroup.test.tsx, packages/webapp/src/administration/users/EditUserGroup.tsx, packages/webapp/src/administration/users/GroupList.test.tsx, packages/webapp/src/administration/users/GroupList.tsx
=> feat(webapp): Show a list of unpublished articles when a group has been deleted

packages/webapp/src/administration/users/EditUserGroup.module.scss, packages/webapp/src/administration/users/EditUserGroup.test.tsx, packages/webapp/src/administration/users/EditUserGroup.tsx
=> feat(webapp): Add save-button to UserGroup Editor

packages/webapp/src/administration/users/DeleteUserGroupDialog.tsx
- user friendliness (see https://github.com/lotta-schule/web/issues/35)
=> feat(webapp): existing file revised to adapt the wording

packages/webapp/src/administration/users/EditUserGroup.tsx
=> spell(webapp): separating two words in adminstration/users/EditUserGroup

packages/hubert/src/tag/tag.module.scss
=> tag roundness and margin: replaced numbers by variables

packages/webapp/src/article/module/text/EditToolbar.module.scss
=> added overflow for edit-toolbar > for mobile devices

packages/hubert/src/dialog/dialog.module.scss, packages/hubert/src/drawer/Drawer.module.scss
=> fix(hubert): Make dialogs full-height on iOS (use 100dvh)

packages/hubert/src/tabs/Tab.module.scss
=> amplified tabbar for mobile devices to 3.5 em

packages/hubert/src/dialog/dialog.module.scss, packages/hubert/src/form/input/Input.module.scss
=> applied variable-colors to dialog style

packages/hubert/src/form/comboBox/ComboBox.test.tsx, packages/hubert/src/form/comboBox/ComboBox.tsx, packages/webapp/src/administration/categories/categories/CategoryEditor.tsx, packages/webapp/src/administration/categories/widgets/WidgetEditor.tsx, packages/webapp/src/administration/users/EditUserPermissionsDialog.tsx, packages/webapp/src/administration/users/UserList.tsx, packages/webapp/src/api/query/SearchUsersAsAdminQuery.graphql, packages/webapp/src/api/schema.graphql, packages/webapp/src/article/editor/EditArticleFooter.tsx, packages/webapp/src/article/preview/ArticlePreview.test.tsx, packages/webapp/src/messaging/CreateMessageDialog.tsx, packages/webapp/src/shared/edit/GroupSelect.module.scss, packages/webapp/src/shared/edit/GroupSelect.test.tsx, packages/webapp/src/shared/edit/GroupSelect.tsx
As it's implemented in the admin user search, it closes #107
=> feat(webapp): GroupSelect now adds an option for a 'None' selection

packages/hubert/src/progress/CircularProgress.tsx
=> adjusted fontSize and deleted textLength

packages/webapp/src/app/(admin)/admin/groups/_component/EditUserGroup.tsx
=> Fix(webapp): Fix problem where opening the admin page of a group could crash app

apps/webapp/src/article/module/audio/AudioAudio.tsx, apps/webapp/src/article/module/audio/Show.test.tsx, apps/webapp/src/article/module/audio/Show.tsx, apps/webapp/src/article/module/image/Image.test.tsx, apps/webapp/src/article/module/image/Image.tsx, apps/webapp/src/article/module/image/ImageImage.tsx, apps/webapp/src/article/module/video/Show.test.tsx, apps/webapp/src/article/module/video/Show.tsx, apps/webapp/src/article/module/video/VideoVideo.tsx, apps/webapp/src/shared/edit/GroupSelect.test.tsx
=> feat(webapp): Do not show multimedia modules if no file is set

apps/webapp/src/messaging/ComposeMessage.test.tsx, apps/webapp/src/messaging/ComposeMessage.tsx
The compose message field does not receive focus every time anymore, but only after sending a new message
Closes #235
=> feat(webapp): Messaging: Compose message should not have autofocus

apps/webapp/src/article/module/image/Config.test.tsx, apps/webapp/src/article/module/image/Config.tsx, apps/webapp/src/article/module/title/Config.tsx
=> feat(webapp): Do not autoclose config of contentmodule image + title

apps/storybook-hubert/src/buttons/PillButton.stories.tsx, libs/hubert/src/avatar/AvatarGroup.module.scss, libs/hubert/src/button/PillButton.module.scss, libs/hubert/src/button/PillButton.test.tsx, libs/hubert/src/button/PillButton.tsx, libs/hubert/src/button/__snapshots__/PillButton.test.tsx.snap, libs/hubert/src/button/index.ts
=> Pill button

apps/webapp/src/article/module/image_collection/Config.tsx
=> Feat(webapp): Do not autoclose ImageCollection Config Dialog when changing config

apps/webapp/src/article/module/image/Image.tsx
=> fix(webapp): Fix problem not showing image contentmodule in editmode

apps/webapp/src/shared/edit/SelectFileButton.tsx, apps/webapp/src/shared/edit/SelectFileOverlay.tsx, libs/hubert/src/browser/Browser.module.scss, libs/hubert/src/dialog/Dialog.module.scss, libs/hubert/src/dialog/Dialog.tsx
=> fix(hubert): Fix File Explorer not being visible when in dialog on safari

apps/webapp/src/article/preview/ArticlePreview.tsx, apps/webapp/src/layout/AppContextProviders.tsx, apps/webapp/src/locale/de.json, apps/webapp/src/pages/_app.tsx, apps/webapp/src/profile/userArticlesDialog/UserArticlesDialog.module.scss, apps/webapp/src/profile/userArticlesDialog/UserArticlesDialog.test.tsx, apps/webapp/src/profile/userArticlesDialog/UserArticlesDialog.tsx
=> feat(webapp): Add list of all article's users to UserArticlesDialog

apps/webapp/src/app/(admin)/admin/general/GeneralSettings.module.scss, apps/webapp/src/app/(admin)/admin/general/GeneralSettings.tsx
=> fixed logo & description overlay for mobile devices

libs/hubert/src/browser/NodeList.module.scss, libs/hubert/src/button/Button.tsx, libs/hubert/src/button/ButtonGroup.module.scss, libs/hubert/src/button/ButtonGroupContext.tsx, libs/hubert/src/dialog/Dialog.tsx
=> Reset ButtonGroupContext in dialogs

apps/core-api/lib/lotta/tenant_migrations/20240826060632_make_usergroup_is_admin_group_not_null.ex, apps/core-api/lib/lotta/tenants/tenant_selector.ex
=> fix(core-api): Database: Make UserGroup.is_admin_group non-nullable

libs/hubert/src/form/select/select.module.scss, libs/hubert/src/menu/ListBox.tsx
=> fix(hubert): Listbox would throw error when it should be focused

apps/core-api/docker-compose.services.yml, apps/core-api/lib/lotta_web/schema/accounts/user.ex
=> fix(core-api): Allow authInfo to return null fields

apps/webapp/src/api/apollo/customFetch.ts, apps/webapp/src/shared/browser/UserBrowser.tsx, apps/webapp/src/util/model/File.tsx
=> fix(webapp): set correct multipart header

libs/hubert/src/form/select/Select.tsx
=> fix(hubert): Limit the height of Select listboxes

apps/webapp/src/app/(admin)/admin/_component/AdminPage.module.scss, libs/hubert/src/form/comboBox/ComboBox.module.scss, libs/hubert/src/form/comboBox/ComboBox.tsx
=> fix(webapp): AdminSection / Users: Make Popovers on Safari not overflow

apps/webapp/src/profile/ProfilePage.tsx, apps/webapp/src/util/model/File.tsx, apps/webapp/src/util/model/User.ts
=> feat(webapp): Use LoadingButton in ProfilePage

apps/webapp/src/shared/dialog/LoginDialog.tsx
=> feat(webapp): Make LoadingButton fail when login fails

apps/webapp/src/app/(admin)/admin/_component/AdminPage.module.scss, apps/webapp/src/app/(admin)/admin/_component/AdminPage.tsx, apps/webapp/src/app/(admin)/admin/categories/layout.tsx, apps/webapp/src/app/(admin)/admin/groups/layout.tsx, apps/webapp/src/app/(admin)/admin/users/UserList.module.scss, apps/webapp/src/app/(admin)/admin/users/page.tsx, apps/webapp/src/app/(admin)/admin/widgets/layout.tsx
=> fix(webapp): AdminPage: Make AdminPage scrollable again

apps/webapp/src/profile/userArticlesDialog/UserArticlesDialog.module.scss
=> fix(webapp): Fix safari shrunking contents of UserArticlesDialog

apps/core-api/config/runtime.exs
=> fix(core-api): Use correct adapter for every env except test

apps/core-api/lib/lotta/analytics.ex
See Sentry Issue:
[CORE-KCW](https://lotta.sentry.io/issues/5158745765/?referrer=github_integration)
=> fix(core-api): Correctly handle bad response from analytics tool

apps/core-api/lib/lotta/guard.ex, apps/core-api/lib/lotta_web/controllers/storage_controller.ex
See Sentry Issue: [CORE-KBE](https://lotta.sentry.io/issues/4389772987/?referrer=github_integration) and
Sentry Issue: [CORE-KBD](https://lotta.sentry.io/issues/4389694812/?referrer=github_integration)
=> fix(core-api): Send 404 when file has not been found, check id format

.github/workflows/release-push.yaml, apps/core-api/lib/lotta/accounts.ex, apps/core-api/lib/lotta/application.ex, apps/core-api/lib/lotta_web/context.ex, apps/core-api/lib/lotta_web/plugs/tenant_plug.ex, apps/core-api/lib/lotta_web/resolvers/article_resolver.ex, apps/webapp/sentry.client.config.ts, apps/webapp/src/api/graphql-env.ts, apps/webapp/src/shared/ServerDataContext.tsx
Fixes Sentry Issue https://lotta.sentry.io/issues/4657934413/events/c1bb5449b7cb4ec7a5ffab331bcf9e3c/
Fixes Sentry Issue https://lotta.sentry.io/issues/4389772987/events/86c51b0cda4a4350888b4b69be55c46b/
Fixes Sentry Issue https://lotta.sentry.io/issues/4394475003/events/df969726910447989a12d160d17c6896/
=> fix(core-api): articles: Better error handling on string -> int conversion  d4027c

.github/workflows/ci.yaml, apps/core-api/lib/lotta_web/resolvers/file_resolver.ex, apps/core-api/lib/lotta_web/schema/accounts.ex
Fixes Sentry error https://lotta.sentry.io/issues/5786882241/events/f2268427c6b04eb1bb37e89b292711c1/
Fixes Sentry error https://lotta.sentry.io/issues/5786580121/events/b695baf458324d3e89ee0f7e5b8cdc53/
=> fix(core-api): file search: Return error instead of crashing for unauthenticated users

apps/webapp/src/category/widgets/calendar/Calendar.test.tsx, apps/webapp/src/category/widgets/calendar/CalendarEntry.tsx, apps/webapp/vitest.config.ts
=> fix(webapp): CalendarWidget: Internal Events: Stop showing times for full-day events

libs/hubert/src/list/DraggableListItem.tsx
=> fix(hubert): SortableDraggableList: Apply dragging styles to children

apps/webapp/src/article/articleReactions/ArticleReactions.test.tsx, apps/webapp/src/article/articleReactions/ArticleReactions.tsx, apps/webapp/src/article/articleReactions/RactionUserList.tsx, apps/webapp/src/article/articleReactions/ReactionCountButtons.tsx, apps/webapp/src/article/articleReactions/ReactionSelector.tsx, apps/webapp/src/test/fixtures/Tenant.ts, libs/hubert/src/button/PillButton.module.scss
=> fix(webapp): Articles: Anon users: Disable "reacting" & "show reactions" buttons

apps/webapp/src/article/module/ContentModule.module.scss, apps/webapp/src/article/relatedArticlesList/ArticlesByTag.tsx, apps/webapp/src/article/relatedArticlesList/ArticlesByUser.tsx, libs/hubert/src/button/ButtonGroup.module.scss, libs/hubert/src/list/List.module.scss
=> 358 vorschlag im bearbeitungsmodus sollten rahmen und toolbar von modulen immer sichtbar sein

apps/webapp/src/article/module/image/ImageContent.module.scss
=> fix(webapp): Image ContentModule: Set image max-width to 100%

apps/webapp/src/app/(admin)/admin/users/page.tsx
=> fix(webapp): Make admin/users page scrollable again

apps/core-api/lib/lotta/calendar/calendar_event.ex, apps/core-api/lib/lotta/calendar/renderer.ex, apps/core-api/lib/lotta/tenant_migrations/20241021202316_add_timezone_to_calendar_events.ex, apps/core-api/lib/lotta/tenants/tenant_db_manager.ex, apps/core-api/lib/lotta_web/schema/calendar.ex, apps/webapp/src/api/graphql-env.ts, apps/webapp/src/app/(admin)/admin/calendars/_component/CreateEventDialog.tsx
=> feat(core-api): Add timezone to calendar events

apps/webapp/src/article/articleReactions/ReactionCountButtons.module.scss, apps/webapp/src/article/articleReactions/ReactionCountButtons.tsx
=> ReactionCount: Add space between icon and counter

apps/webapp/src/app/(admin)/admin/calendars/_hook/useUnfoldedEvents.ts
=> fix(webapp): Stop showing past recurring events in Calendar widget

apps/webapp/src/app/(admin)/admin/widgets/_component/configuration/CalendarConfiguration.tsx, apps/webapp/src/app/(admin)/admin/widgets/_component/configuration/CalendarWidgetConfiguration.tsx
=> fix(webapp): Allow to set an external calendar

apps/webapp/src/article/module/text/EditToolbar.tsx, apps/webapp/src/layout/Main.module.scss
Use navigation height as top property
=> fix(webapp): Make sticky EditToolbar for text module be sticky again 💦

apps/webapp/src/app/(admin)/admin/categories/_component/CategoryNavigation.tsx
=> fix(webapp): Administration: Save changes made to subcategories sorting

libs/hubert/src/form/comboBox/ComboBox.tsx, libs/hubert/src/form/select/Select.tsx, libs/hubert/src/popover/PopoverContent.tsx
=> fix(hubert): Set correct size for PopoverContent

apps/webapp/src/api/graphql-env.ts, apps/webapp/src/util/model/File.tsx
=> fix(webapp): Correctly compute url of files' "original" format

apps/webapp/src/component/form/SearchUserField.module.scss, apps/webapp/src/component/form/SearchUserField.tsx, libs/hubert/src/form/comboBox/ComboBox.tsx
=> fix(webapp): Make SearchUserField suggestions visible again

apps/core-api/lib/lotta/storage/storage.ex, apps/webapp/src/app/(admin)/admin/constraints/ConstraintsList.test.tsx, apps/webapp/src/app/(admin)/admin/constraints/ConstraintsList.tsx
=> fix(web): user space constraint is now saved with correct value

apps/webapp/src/api/query/SearchDirectoriesAndFiles.graphql
=> fix(web): Get format availability for file search results

apps/webapp/src/app/(admin)/admin/users/UserList.tsx, apps/webapp/src/loader/loadTenant.ts
=> fix(web): UserList: Correctly filter for users without groups

apps/webapp/src/article/preview/ArticlePreview.module.scss, apps/webapp/src/article/preview/ArticlePreview.tsx
=> feat(web): Make article pins more distinguishible

.github/workflows/__deploy_dockerfile.yaml, apps/webapp/src/layout/navigation/Navbar.module.scss, libs/hubert/src/avatar/Avatar.module.scss, libs/hubert/src/avatar/Avatar.tsx, libs/hubert/src/list/__snapshots__/List.test.tsx.snap
=> feat(web): Optimize avatar-style for interaction
